import type { Metadata } from "next";
import { Indie_Flower, Inter, Raleway, The_Girl_Next_Door } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";
import { ThemeProvider } from "next-themes";
import ReactQueryProvider from "./ReactQueryProvider";
import Providers from "@/providers/ProgressbarProvider";
import {NextSSRPlugin} from "@uploadthing/react/next-ssr-plugin"
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";
const inter = Inter({ subsets: ["latin"] });
const cute = The_Girl_Next_Door({ subsets:["latin"],
  weight:"400",
  variable:"--font-cute"
 });
 const cute1 = Raleway({ subsets:["latin"],
  weight:"400",
  variable:"--font-cute1"
 });



export const metadata: Metadata = {
  title: "Catsagtram",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className ,cute.variable,cute1.variable,"bg-background")}>
        <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)}/>
        <ReactQueryProvider>
        <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
        >
          <Providers>
          {children}
          </Providers>
     
        </ThemeProvider>
        <Toaster/>
        </ReactQueryProvider>
        
      </body>
    </html>
  );
}
